### PR TITLE
Add context for catalog search to allow local export

### PR DESCRIPTION
**Pull request by thomasmassmann**
The browser view is already registered for all content. With the additional path query we can export items in a local tree.

### CODE REVIEW

**Comment by thomasmassmann** [comment]
@pbauer , can you please take a look if this is ok for you?

**Comment by fredvd** [comment]
@thomasmassmann  @pbauer This was exactly what I was expecting to happen when I called the view on a subfolder.  Only export the content from that path. Instead I got all File CT's from a site in my .zip  :-O

**Comment by pbauer** [comment]
I was very confused since I was sure I implemented that feature already and it tool me a while to realize that this is collective.contentexport and not collective.exportimport 😆

**Comment by fredvd** [comment]
@thomasmassmann Your fix works for exporting Excel, but When I try to export file objects from a subtree/section the form lists only 5 CT's, but still exports all CT's in the site (152 in my case).  I'll look into it.

**Comment by fredvd** [comment]
Fixed on master for image/files to zip. :-)

**Pull request merged**
